name: Deploy API

on:
  push:
    branches:
      - master
      - dev

jobs:
   docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PAT: ${{secrets.DOCKER_PAT}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PAT 
      - name: Build and Push API Image
        working-directory: .
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          docker build -t ${{secrets.DOCKER_USER}}/techchallenge:latest -t ${{secrets.DOCKER_USER}}/techchallenge:$TAG . --no-cache
          docker push ${{secrets.DOCKER_USER}}/techchallenge:$TAG
          docker push ${{secrets.DOCKER_USER}}/techchallenge:latest    
          
   deploy-aws:    
   
     needs: docker-build
  
     if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main'
     
     environment:
        name: prod  
        
     runs-on: ubuntu-latest
     
     steps:
      - name: Enviar evento repository_dispatch para repositório do k8s
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: 'andersonssilveira96',
              repo: '6SOAT-Fase03-k8s',
              event_type: 'deployment'
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
