name: Deploy API

on:
 pull_request:
    types:
      - closed
    branches:
      - master 

jobs:
   docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PAT: ${{secrets.DOCKER_PAT}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PAT 
      - name: Build and Push API Image
        working-directory: .
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          docker build -t ${{secrets.DOCKER_USER}}/techchallenge:latest -t ${{secrets.DOCKER_USER}}/techchallenge:$TAG . --no-cache
          docker push ${{secrets.DOCKER_USER}}/techchallenge:$TAG
          docker push ${{secrets.DOCKER_USER}}/techchallenge:latest    
          
   deploy-aws:      
     needs: docker-build             
     runs-on: ubuntu-latest     
     steps:
      - name: Deploy EKS
        env:
          TOKEN: ${{ secrets.GTH_TOKEN  }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/andersonssilveira96/6SOAT-Fase03-k8s/actions/workflows/k8s.yml/dispatches \
          -d '{"ref":"master"}'
